Feat(#20): Business Exception 및 ExceptionCode 정의
slate-movte/slate-back pull request #21
Opened 2023-08-26 12:09 UTC by JoeSeongchan

- Runtime Exception을 상속하는 Business Exception 정의
- HttpBusinessException은 BusinessException을 상속하고, BadRequestException과 같이 HttpStatusCode 정보를 가진 Exception이 HttpBusinessException을 상속하게 함

![image](https://github.com/slate-movte/slate-back/assets/63490601/3bbb5259-f748-49ef-a6b0-dd9a9494f6de)

Closes: #20

2023-08-26 13:18 UTC, InHyeok-J requested changes
응답 부분은 수정 부탁드릴게여~

2023-08-26 13:18 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/response/ResponseFactory.java
> +
빈 객체까지의 책임이 없을것 같아서 Utils 정도.. 
ex) statis method 여러개 정도면 될것같다는 생각이듭니다!

2023-08-26 13:18 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/response/ResponseFactory.java
> +        body.put("message", e.getMessage());
에러 형태도 DTO를 사용하면 좋을것 같습니다!

2023-08-26 13:18 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/response/ResponseFormat.java
> +}
해당 코드가 성공 / 실패 둘다 쓰는것 같은데 그러면 JSON Ignore 같은 설정이 추가되어야 할 것 같습니다 ! 
```yml
data : {} // 단건 데이터 있음 성공
data : null // 단건 데이터 없음

data : [{},{},{},{},{}] 
data : [] // 리스트 데이터 조회시 데이터 결과값 없음.
```
그리고 성공시 data가 있는데 이 케이스가 고려해야 할 것 같아요

2023-08-26 13:18 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/exception/UnauthorizedException.java
> +}
code랑 exception에 해당 부분에 왜 있는지 궁금하네요 !!

2023-08-29 01:01 UTC, JoeSeongchan commented on src/main/java/com/movte/slate/global/exception/UnauthorizedException.java
> +}
UnauthorizedException이 발생했을 때, 그 Exception이 Token Expired 때문에 발생했는지 확인하는 책임을 Exception에게 부여하기 위해 해당 코드를 넣었습니다.

2023-08-29 01:07 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/exception/UnauthorizedExceptionCode.java
> +    private final String descriptionMessage;
댓글에 없지만 얘기했던 부분인데 code를 String으로 바꾸셔야 합니다

2023-08-29 01:07 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/response/FailResponseFormat.java
> +    private final Long code;
해당 DTO의 naming을 format으로 사용하는데 저희 DTO 네이밍을 정해봐야할것 같네요

2023-08-29 01:15 UTC, JoeSeongchan commented on src/main/java/com/movte/slate/global/exception/UnauthorizedExceptionCode.java
> +    private final String descriptionMessage;
세 자리 코드로 만들겠습니다. 001, 002 이런 식으로요.

2023-08-29 01:19 UTC, JoeSeongchan commented on src/main/java/com/movte/slate/global/exception/UnauthorizedExceptionCode.java
> +    private final String descriptionMessage;
바꿨습니다.

2023-08-29 01:19 UTC, JoeSeongchan commented on src/main/java/com/movte/slate/global/response/FailResponseFormat.java
> +    private final Long code;
언제 얘기해볼까요?

2023-08-29 01:21 UTC, InHyeok-J commented on src/main/java/com/movte/slate/global/response/FailResponseFormat.java
> +    private final Long code;
MM으로 진행해보죠

2023-08-29 10:34 UTC, qudtjs0753 reviewed
고생하셨습니다!!

2023-08-29 10:34 UTC, qudtjs0753 commented on src/main/java/com/movte/slate/global/exception/HttpBusinessException.java
> +public abstract class HttpBusinessException extends BusinessException {
status 로직에 대해 `HttpBusinessException`을 따로 두신 게 좋은거같아요!

2023-08-29 10:34 UTC, InHyeok-J approved these changes

2023-08-29 10:35 UTC, merged